### PR TITLE
Open gist dialog

### PR DESCRIPTION
**Pull request by opcodewriter**
Implemented open gist dialog

https://github.com/gist-run/gist-run/issues/20

### CODE REVIEW

**Comment by jdanyow** [comment]
@opcodewriter apologies for the delay in reviewing this.  Was out of town last week and will be out of town again tomorrow-Sunday.  Will review asap next week.

**Comment by opcodewriter** [comment]
thank you, eager about your feedback

**Comment by opcodewriter** [comment]
been ~ 20 days, just wondering what do you think

**Comment by opcodewriter** [comment]
LOL, you said you're interested about it, I worked on it, and then just went quiet.

**Comment by jdanyow** [comment]
@opcodewriter it looks like a good first pass, here's some feedback:

1. code conventions: please follow the existing code conventions- 2 space tabs, etc
2. fetching gists: users may have multiple pages of gists, need to support that somehow
3. dependencies:  I don't want to take any additional dependencies unless truly necessary. No need for aurelia-dialog.
4. in my testing, selecting the gist didn't load the gist in gist.run.  Is there more work to do there?
5. search results: I'd like to show more info about the gists in the search results- perhaps the names of the first X files?

**Comment by jdanyow** [comment]
It's a shame there's no API for gist search yet.  Would love to provide this functionality without actually brute force writing it:
search
https://gist.github.com/search

**Comment by opcodewriter** [comment]
Thanks for the feedback.
About fetching gists. unfortunately the Gist API doesn't have support for pagination, it returns all of them. Optionally, it can return gists updated after a specific date. See https://developer.github.com/v3/gists/#list-a-users-gists
But I can't see a way to know which date to use for a user. For a date back 30 days ago, it can return no gists. But still it might be a good idea instead of returning all gist. 
User can instead rely on the search.
Or, just give up on this idea completely...

**Comment by jdanyow** [comment]
The response headers tell how to access the next page of gists and how many pages there are:

gists
https://api.github.com/users/jdanyow/gists

**Comment by opcodewriter** [comment]
OK, I didn't notice the Link header before, thanks.

About the aurelia-dialog: What's wrong with it? I see it's a project started by Rob and another Aurelia team member.
What's the better option? Implement a similar functionality from scratch?

**Comment by opcodewriter** [comment]
OK, I will give up :) 
I thought you wanted contributions to the project. I'm sorry but that's not possible you're not willing to communicate. 
It makes sense to agree on few minimum things before I spent time working, otherwise it's going to be useless. Anyway, thank you for your time, I learned few things.

**Comment by opcodewriter** [comment]
alright, I'm giving up on this. for some reason, you're not being responsive. 
all I needed was some little feedback so I won't work on something which you won't going to accept.
anyways, thanks, I learned a few things

**Pull request closed without merging**
